require("sama.plugins-setup") -- keep at the top
require("sama.core.colorscheme")
require("sama.core.options")
require("sama.core.keymaps")
require("sama.plugins.comment")
require("sama.plugins.nvim-tree")
require("sama.plugins.lualine")
require("sama.plugins.telescope")
require("sama.plugins.nvim-cmp")
require("sama.plugins.lsp.mason")
require("sama.plugins.lsp.lspsaga")
require("sama.plugins.lsp.lspconfig")
require("sama.plugins.lsp.null-ls")
require("sama.plugins.autopairs")
require("sama.plugins.treesitter")
require("sama.plugins.gitsigns")
require("sama.plugins.whichkey")
require("sama.plugins.tabout")
require("sama.plugins.js-dap")
<<<<<<< HEAD
require("sama.plugins.harpoon")
require("sama.plugins.nvim-ufo")
=======
>>>>>>> parent of 1432812 (added plugins harpoon and surround)
